kind: pipeline
name: default

type: docker
steps:
  - name: test
    image: maven:3-openjdk-11
    commands:
      - mvn install -Dmaven.javadoc.skip=true -DskipTests -Dgpg.skip -B -V
      - mvn test -B
  - name: report
    image: maven:3-openjdk-11
    environment:
      repoToken:
        from_secret: repo_token
    commands:
      - mvn install -Dmaven.javadoc.skip=true -DskipTests -Dgpg.skip -B -V
      - mvn clean test jacoco:report coveralls:report -DrepoToken=$repoToken
