kind: pipeline
name: default

type: docker
steps:
  - name: test
    image: maven:3-openjdk-11
    commands:
      - mvn install -Dmaven.javadoc.skip=true -DskipTests -Dgpg.skip -B -V
      - mvn test -B
      - mvn clean test jacoco:report coveralls:report
